import { ServiceType } from '$lib/types'

type IconLookup = Record<ServiceType, string>

const SERVICE_TYPE_TO_ICON: IconLookup = {
  [ServiceType.EC2]: 'Compute/EC2.svg',
  [ServiceType.ECS]: 'Containers/Elastic-Container-Service.svg',
  [ServiceType.EKS]: 'Containers/Elastic-Kubernetes-Service.svg',
  [ServiceType.LAMBDA]: 'Compute/Lambda.svg',
  [ServiceType.FARGATE]: 'Compute/Fargate.svg',
  [ServiceType.BATCH]: 'Compute/Batch.svg',
  [ServiceType.ELASTIC_BEANSTALK]: 'Compute/Elastic-Beanstalk.svg',
  [ServiceType.APP_RUNNER]: 'Containers/App-Runner.svg',
  [ServiceType.ECR]: 'Containers/Elastic-Container-Registry.svg',
  [ServiceType.ECS_ANYWHERE]: 'Containers/ECS-Anywhere.svg',
  [ServiceType.EKS_ANYWHERE]: 'Containers/EKS-Anywhere.svg',
  [ServiceType.S3]: 'Storage/Simple-Storage-Service.svg',
  [ServiceType.EFS]: 'Storage/EFS.svg',
  [ServiceType.EBS]: 'Storage/Elastic-Block-Store.svg',
  [ServiceType.FSX]: 'Storage/FSx.svg',
  [ServiceType.STORAGE_GATEWAY]: 'Storage/Storage-Gateway.svg',
  [ServiceType.BACKUP]: 'Storage/Backup.svg',
  [ServiceType.S3_GLACIER]: 'Storage/Simple-Storage-Service-Glacier.svg',
  [ServiceType.RDS]: 'Database/RDS.svg',
  [ServiceType.DYNAMODB]: 'Database/DynamoDB.svg',
  [ServiceType.ELASTICACHE]: 'Database/ElastiCache.svg',
  [ServiceType.VALKEY]: 'Database/ElastiCache.svg',
  [ServiceType.AURORA]: 'Database/Aurora.svg',
  [ServiceType.NEPTUNE]: 'Database/Neptune.svg',
  [ServiceType.DOCUMENTDB]: 'Database/DocumentDB.svg',
  [ServiceType.KEYSPACES]: 'Database/Keyspaces.svg',
  [ServiceType.TIMESTREAM]: 'Database/Timestream.svg',
  [ServiceType.MEMORYDB]: 'Database/MemoryDB-for-Redis.svg',
  [ServiceType.QLDB]: 'Database/Quantum-Ledger-Database.svg',
  [ServiceType.VPC]: 'Networking-Content-Delivery/Virtual-Private-Cloud.svg',
  [ServiceType.CLOUDFRONT]: 'Networking-Content-Delivery/CloudFront.svg',
  [ServiceType.ROUTE53]: 'Networking-Content-Delivery/Route-53.svg',
  [ServiceType.API_GATEWAY]: 'App-Integration/API-Gateway.svg',
  [ServiceType.DIRECT_CONNECT]: 'Networking-Content-Delivery/Direct-Connect.svg',
  [ServiceType.APP_MESH]: 'Networking-Content-Delivery/App-Mesh.svg',
  [ServiceType.CLOUD_MAP]: 'Networking-Content-Delivery/Cloud-Map.svg',
  [ServiceType.GLOBAL_ACCELERATOR]: 'Networking-Content-Delivery/Global-Accelerator.svg',
  [ServiceType.ALB]: 'Networking-Content-Delivery/Elastic-Load-Balancing.svg',
  [ServiceType.NLB]: 'Networking-Content-Delivery/Elastic-Load-Balancing.svg',
  [ServiceType.ELB]: 'Networking-Content-Delivery/Elastic-Load-Balancing.svg',
  [ServiceType.ELASTIC_LOAD_BALANCING]: 'Networking-Content-Delivery/Elastic-Load-Balancing.svg',
  [ServiceType.SQS]: 'App-Integration/Simple-Queue-Service.svg',
  [ServiceType.SNS]: 'App-Integration/Simple-Notification-Service.svg',
  [ServiceType.EVENTBRIDGE]: 'App-Integration/EventBridge.svg',
  [ServiceType.EVENTBRIDGE_RULE]: 'App-Integration/EventBridge.svg',
  [ServiceType.STEP_FUNCTIONS]: 'App-Integration/Step-Functions.svg',
  [ServiceType.SWF]: 'App-Integration/Step-Functions.svg',
  [ServiceType.MQ]: 'App-Integration/MQ.svg',
  [ServiceType.APPSYNC]: 'Front-End-Web-Mobile/AppSync.svg',
  [ServiceType.KINESIS]: 'Analytics/Kinesis.svg',
  [ServiceType.KINESIS_FIREHOSE]: 'Analytics/Kinesis-Firehose.svg',
  [ServiceType.KINESIS_ANALYTICS]: 'Analytics/Kinesis-Data-Analytics.svg',
  [ServiceType.ATHENA]: 'Analytics/Athena.svg',
  [ServiceType.EMR]: 'Analytics/EMR.svg',
  [ServiceType.GLUE]: 'Analytics/Glue.svg',
  [ServiceType.REDSHIFT]: 'Analytics/Redshift.svg',
  [ServiceType.QUICKSIGHT]: 'Analytics/QuickSight.svg',
  [ServiceType.OPENSEARCH]: 'Analytics/OpenSearch-Service.svg',
  [ServiceType.MSK]: 'Analytics/Managed-Streaming-for-Apache-Kafka.svg',
  [ServiceType.IAM]: 'Security-Identity-Compliance/Identity-and-Access-Management.svg',
  [ServiceType.COGNITO]: 'Security-Identity-Compliance/Cognito.svg',
  [ServiceType.SECRETS_MANAGER]: 'Security-Identity-Compliance/Secrets-Manager.svg',
  [ServiceType.KMS]: 'Security-Identity-Compliance/Key-Management-Service.svg',
  [ServiceType.WAF]: 'Security-Identity-Compliance/WAF.svg',
  [ServiceType.SHIELD]: 'Security-Identity-Compliance/Shield.svg',
  [ServiceType.GUARDDUTY]: 'Security-Identity-Compliance/GuardDuty.svg',
  [ServiceType.INSPECTOR]: 'Security-Identity-Compliance/Inspector.svg',
  [ServiceType.MACIE]: 'Security-Identity-Compliance/Macie.svg',
  [ServiceType.SECURITY_HUB]: 'Security-Identity-Compliance/Security-Hub.svg',
  [ServiceType.CERTIFICATE_MANAGER]: 'Security-Identity-Compliance/Certificate-Manager.svg',
  [ServiceType.FIREWALL_MANAGER]: 'Security-Identity-Compliance/Firewall-Manager.svg',
  [ServiceType.NETWORK_FIREWALL]: 'Security-Identity-Compliance/Network-Firewall.svg',
  [ServiceType.CLOUDWATCH]: 'Management-Governance/CloudWatch.svg',
  [ServiceType.CLOUDTRAIL]: 'Management-Governance/CloudTrail.svg',
  [ServiceType.CONFIG]: 'Management-Governance/Config.svg',
  [ServiceType.SYSTEMS_MANAGER]: 'Management-Governance/Systems-Manager.svg',
  [ServiceType.CLOUDFORMATION]: 'Management-Governance/CloudFormation.svg',
  [ServiceType.ORGANIZATIONS]: 'Management-Governance/Organizations.svg',
  [ServiceType.CONTROL_TOWER]: 'Management-Governance/Control-Tower.svg',
  [ServiceType.TRUSTED_ADVISOR]: 'Management-Governance/Trusted-Advisor.svg',
  [ServiceType.CODECOMMIT]: 'Developer-Tools/CodeCommit.svg',
  [ServiceType.CODEBUILD]: 'Developer-Tools/CodeBuild.svg',
  [ServiceType.CODEDEPLOY]: 'Developer-Tools/CodeDeploy.svg',
  [ServiceType.CODEPIPELINE]: 'Developer-Tools/CodePipeline.svg',
  [ServiceType.CODEARTIFACT]: 'Developer-Tools/CodeArtifact.svg',
  [ServiceType.CLOUD9]: 'Developer-Tools/Cloud9.svg',
  [ServiceType.X_RAY]: 'Developer-Tools/X-Ray.svg',
  [ServiceType.SAGEMAKER]: 'Machine-Learning/SageMaker.svg',
  [ServiceType.COMPREHEND]: 'Machine-Learning/Comprehend.svg',
  [ServiceType.REKOGNITION]: 'Machine-Learning/Rekognition.svg',
  [ServiceType.TEXTRACT]: 'Machine-Learning/Textract.svg',
  [ServiceType.TRANSLATE]: 'Machine-Learning/Translate.svg',
  [ServiceType.TRANSCRIBE]: 'Machine-Learning/Transcribe.svg',
  [ServiceType.POLLY]: 'Machine-Learning/Polly.svg',
  [ServiceType.LEX]: 'Machine-Learning/Lex.svg',
  [ServiceType.DMS]: 'Migration-Transfer/Database-Migration-Service.svg',
  [ServiceType.TRANSFER_FAMILY]: 'Migration-Transfer/Transfer-Family.svg',
  [ServiceType.MIGRATION_HUB]: 'Migration-Transfer/Migration-Hub.svg',
  [ServiceType.DATASYNC]: 'Migration-Transfer/DataSync.svg',
  [ServiceType.SNOWBALL]: 'Migration-Transfer/Snowball.svg',
  [ServiceType.AMPLIFY]: 'Front-End-Web-Mobile/Amplify.svg'
}

export function getAwsIconPath(serviceType?: ServiceType | null): string | null {
  if (!serviceType) {
    return null
  }
  const file = SERVICE_TYPE_TO_ICON[serviceType]
  return file ? `/icons/aws/${file}` : null
}

