import { ServiceType } from '~/types'

export type ServiceCategory = 'cloud' | 'database' | 'disk' | 'internet' | 'server'

const CATEGORY_LOOKUP: Record<ServiceType, ServiceCategory> = {
  [ServiceType.EC2]: 'server',
  [ServiceType.ECS]: 'server',
  [ServiceType.EKS]: 'server',
  [ServiceType.LAMBDA]: 'server',
  [ServiceType.FARGATE]: 'server',
  [ServiceType.BATCH]: 'cloud',
  [ServiceType.ELASTIC_BEANSTALK]: 'cloud',
  [ServiceType.APP_RUNNER]: 'cloud',
  [ServiceType.ECR]: 'server',
  [ServiceType.ECS_ANYWHERE]: 'cloud',
  [ServiceType.EKS_ANYWHERE]: 'cloud',
  [ServiceType.S3]: 'disk',
  [ServiceType.EFS]: 'disk',
  [ServiceType.EBS]: 'disk',
  [ServiceType.FSX]: 'disk',
  [ServiceType.STORAGE_GATEWAY]: 'disk',
  [ServiceType.BACKUP]: 'disk',
  [ServiceType.S3_GLACIER]: 'disk',
  [ServiceType.RDS]: 'database',
  [ServiceType.DYNAMODB]: 'database',
  [ServiceType.ELASTICACHE]: 'database',
  [ServiceType.VALKEY]: 'database',
  [ServiceType.AURORA]: 'database',
  [ServiceType.NEPTUNE]: 'database',
  [ServiceType.DOCUMENTDB]: 'database',
  [ServiceType.KEYSPACES]: 'database',
  [ServiceType.TIMESTREAM]: 'database',
  [ServiceType.MEMORYDB]: 'database',
  [ServiceType.QLDB]: 'database',
  [ServiceType.VPC]: 'internet',
  [ServiceType.CLOUDFRONT]: 'internet',
  [ServiceType.ROUTE53]: 'internet',
  [ServiceType.API_GATEWAY]: 'internet',
  [ServiceType.DIRECT_CONNECT]: 'internet',
  [ServiceType.APP_MESH]: 'internet',
  [ServiceType.CLOUD_MAP]: 'internet',
  [ServiceType.GLOBAL_ACCELERATOR]: 'internet',
  [ServiceType.ALB]: 'internet',
  [ServiceType.NLB]: 'internet',
  [ServiceType.ELB]: 'internet',
  [ServiceType.ELASTIC_LOAD_BALANCING]: 'internet',
  [ServiceType.SQS]: 'internet',
  [ServiceType.SNS]: 'internet',
  [ServiceType.EVENTBRIDGE]: 'internet',
  [ServiceType.EVENTBRIDGE_RULE]: 'internet',
  [ServiceType.STEP_FUNCTIONS]: 'internet',
  [ServiceType.SWF]: 'internet',
  [ServiceType.MQ]: 'internet',
  [ServiceType.APPSYNC]: 'internet',
  [ServiceType.KINESIS]: 'internet',
  [ServiceType.KINESIS_FIREHOSE]: 'internet',
  [ServiceType.KINESIS_ANALYTICS]: 'internet',
  [ServiceType.ATHENA]: 'cloud',
  [ServiceType.EMR]: 'cloud',
  [ServiceType.GLUE]: 'cloud',
  [ServiceType.REDSHIFT]: 'database',
  [ServiceType.QUICKSIGHT]: 'cloud',
  [ServiceType.OPENSEARCH]: 'database',
  [ServiceType.MSK]: 'internet',
  [ServiceType.IAM]: 'cloud',
  [ServiceType.COGNITO]: 'internet',
  [ServiceType.SECRETS_MANAGER]: 'cloud',
  [ServiceType.KMS]: 'cloud',
  [ServiceType.WAF]: 'internet',
  [ServiceType.SHIELD]: 'internet',
  [ServiceType.GUARDDUTY]: 'cloud',
  [ServiceType.INSPECTOR]: 'cloud',
  [ServiceType.MACIE]: 'cloud',
  [ServiceType.SECURITY_HUB]: 'cloud',
  [ServiceType.CERTIFICATE_MANAGER]: 'internet',
  [ServiceType.FIREWALL_MANAGER]: 'internet',
  [ServiceType.NETWORK_FIREWALL]: 'internet',
  [ServiceType.CLOUDWATCH]: 'cloud',
  [ServiceType.CLOUDTRAIL]: 'cloud',
  [ServiceType.CONFIG]: 'cloud',
  [ServiceType.SYSTEMS_MANAGER]: 'cloud',
  [ServiceType.CLOUDFORMATION]: 'cloud',
  [ServiceType.ORGANIZATIONS]: 'cloud',
  [ServiceType.CONTROL_TOWER]: 'cloud',
  [ServiceType.TRUSTED_ADVISOR]: 'cloud',
  [ServiceType.CODECOMMIT]: 'cloud',
  [ServiceType.CODEBUILD]: 'cloud',
  [ServiceType.CODEDEPLOY]: 'cloud',
  [ServiceType.CODEPIPELINE]: 'cloud',
  [ServiceType.CODEARTIFACT]: 'cloud',
  [ServiceType.CLOUD9]: 'cloud',
  [ServiceType.X_RAY]: 'cloud',
  [ServiceType.SAGEMAKER]: 'cloud',
  [ServiceType.COMPREHEND]: 'cloud',
  [ServiceType.REKOGNITION]: 'cloud',
  [ServiceType.TEXTRACT]: 'cloud',
  [ServiceType.TRANSLATE]: 'cloud',
  [ServiceType.TRANSCRIBE]: 'cloud',
  [ServiceType.POLLY]: 'cloud',
  [ServiceType.LEX]: 'cloud',
  [ServiceType.DMS]: 'cloud',
  [ServiceType.TRANSFER_FAMILY]: 'internet',
  [ServiceType.MIGRATION_HUB]: 'cloud',
  [ServiceType.DATASYNC]: 'internet',
  [ServiceType.SNOWBALL]: 'disk',
  [ServiceType.AMPLIFY]: 'cloud'
}

export function getServiceCategory(serviceType: ServiceType): ServiceCategory {
  return CATEGORY_LOOKUP[serviceType] ?? 'server'
}

